apiVersion: v2
name: highland
description: Secure Kubernetes storage control plane for CSI, Longhorn, Rook/Ceph, and OpenEBS
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - longhorn
  - csi
  - ceph
  - rook
  - openebs
  - storage
  - highland
maintainers:
  - name: Highland
home: https://github.com/alphabravo-oss/highland
icon: https://raw.githubusercontent.com/alphabravo-oss/highland/main/apps/web/public/favicon.svg
sources:
  - https://github.com/alphabravo-oss/highland
dependencies:
  - name: longhorn
    alias: embeddedLonghorn
    version: "1.12.0"
    repository: https://charts.longhorn.io
    condition: embeddedLonghorn.enabled
