apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "highland.fullname" . }}-config
  labels:
    {{- include "highland.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "listenAddr": ":8080",
      "managerUrl": {{ include "highland.managerUrl" . | quote }},
      "authMode": {{ .Values.config.authMode | quote }},
      "localAlways": {{ .Values.config.localAlways }},
      "cookieName": {{ .Values.config.cookieName | quote }},
      "cookieSecure": {{ .Values.config.cookieSecure }},
      "sessionTTL": {{ .Values.config.sessionTTL | quote }},
      "metricsInterval": {{ .Values.config.metricsInterval | quote }},
      "oidcMock": {{ .Values.config.oidcMock }},
      "version": {{ .Values.config.version | quote }},
      "oidcIssuer": {{ .Values.auth.oidc.issuerURL | quote }},
      "oidcClientId": {{ .Values.auth.oidc.clientID | quote }},
      "oidcRedirectUrl": {{ .Values.auth.oidc.redirectURL | quote }},
      "allowedOrigins": {{ .Values.config.allowedOrigins | quote }}
    }
