#!/usr/bin/env bash
# Bundle highland-v1 and generate Go + TypeScript wire artifacts (ADR-0007).
# Deterministic after tools are installed; CI fails on dirty git diff.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

REDOCLY_VERSION="${REDOCLY_VERSION:-2.18.0}"
# Pin generators (override via env for local experiments).
OAPI_CODEGEN_VERSION="${OAPI_CODEGEN_VERSION:-v2.4.1}"
OPENAPI_TS_VERSION="${OPENAPI_TS_VERSION:-7.6.1}"

BUNDLE_DIR="docs/openapi/generated"
BUNDLE="$BUNDLE_DIR/highland-v1.bundled.yaml"
GO_OUT="apps/api/internal/api/gen/highland.gen.go"
TS_OUT="apps/web/src/api/generated/highland-v1.ts"

mkdir -p "$BUNDLE_DIR" "$(dirname "$GO_OUT")" "$(dirname "$TS_OUT")"

echo "== bundle highland-v1 (redocly@${REDOCLY_VERSION}) =="
npx --yes "@redocly/cli@${REDOCLY_VERSION}" bundle docs/openapi/highland-v1.yaml \
  --config redocly.yaml \
  -o "$BUNDLE"

echo "== generate Go types (oapi-codegen@${OAPI_CODEGEN_VERSION}) =="
GOBIN="${GOBIN:-$(go env GOPATH)/bin}"
export PATH="$GOBIN:$PATH"
if ! command -v oapi-codegen >/dev/null 2>&1; then
  go install "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@${OAPI_CODEGEN_VERSION}"
fi
# types only — handlers remain handwritten; package gen under internal/api/gen
oapi-codegen \
  -generate types \
  -package gen \
  -o "$GO_OUT" \
  "$BUNDLE"

# Header for humans / drift policy
{
  echo "// Code generated by oapi-codegen (${OAPI_CODEGEN_VERSION}); DO NOT EDIT."
  echo "// Source: docs/openapi/highland-v1.yaml (bundled)."
  echo "// Regenerate: ./hack/openapi-generate.sh"
  echo
  cat "$GO_OUT"
} >"$GO_OUT.tmp"
mv "$GO_OUT.tmp" "$GO_OUT"

echo "== generate TypeScript types (openapi-typescript@${OPENAPI_TS_VERSION}) =="
# Use an empty config so redocly.yaml's `apis:` block does not force multi-schema mode.
npx --yes "openapi-typescript@${OPENAPI_TS_VERSION}" "$BUNDLE" \
  -c /dev/null \
  -o "$TS_OUT"
# Prepend header (openapi-typescript may already emit a comment)
if ! head -1 "$TS_OUT" | grep -qiE 'generated|DO NOT EDIT'; then
  {
    echo "/**"
    echo " * Generated by openapi-typescript@${OPENAPI_TS_VERSION}; DO NOT EDIT."
    echo " * Source: docs/openapi/highland-v1.yaml (bundled)."
    echo " * Regenerate: ./hack/openapi-generate.sh"
    echo " */"
    cat "$TS_OUT"
  } >"$TS_OUT.tmp"
  mv "$TS_OUT.tmp" "$TS_OUT"
fi

echo "OK: generated"
echo "  $BUNDLE"
echo "  $GO_OUT"
echo "  $TS_OUT"
