apiVersion: highland.io/v1alpha1
kind: HighlandPolicy
metadata:
  name: highland
spec:
  storage:
    acceptNewOperations: true
    portableKubernetesWrites: false
    portableKubernetesProviderIds: []
    longhornWrites: false
    rookCephWrites: true
    allowCephStorageClassDelete: false
    allowCephPoolDelete: false
